version: '3.9'


services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo-database
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
    volumes:
      - .:/home/

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: user
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: user
  #     ME_CONFIG_MONGODB_URL: mongodb://user:user@mongo:27017/
